Repository logstash-plugins/logstash-input-tcp, pull requests merged in 2023-06, with the labels that each got.

#212 bump netty to 4.1.93
  CHANGELOG.md
  build.gradle
  version
Labels: status:needs-review

#214 reduce error logging on connection resets
  CHANGELOG.md
  src/main/java/org/logstash/tcp/InputLoop.java
  version
Labels: int-shortlist, status:changes-requested

#216 update netty to 4.1.94 and other dependencies
  CHANGELOG.md
  build.gradle
  version
Labels: status:approved
